/**
 * CortexMD Drug Database v2
 * Auto-generated by migrate-drugs-to-v2.ts
 * Generated: 2026-04-09T20:01:59.291Z
 *
 * DO NOT EDIT MANUALLY — re-run migration script to update.
 */

import type { DrugSchemaV2 } from '../types/pharmacology';

export const DRUGS_V2: Record<string, DrugSchemaV2> = {
  "sertraline": {
    "id": "sertraline",
    "brand_name": "Zoloft",
    "generic_name": "sertraline",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "SERT",
        "ki_nM": 0.29,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "DAT",
        "ki_nM": 25,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "NET",
        "ki_nM": 420,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "s1",
        "ki_nM": 35,
        "type": "inverse_agonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#60a5fa",
    "region_targets": [
      "dlPFC",
      "amygdala",
      "hippo",
      "vta",
      "nac",
      "vmPFC",
      "acc",
      "raphe",
      "brainstem",
      "spinal"
    ],
    "legacy_short": "СЕРТ",
    "legacy_name_ru": "Золофт",
    "doses": [
      25,
      50,
      75,
      100,
      150,
      200
    ],
    "default_dose": 100,
    "dose_unit": "мг",
    "warn_dose": 150,
    "max_dose": 200,
    "warn_text": "Серотониновый синдром при комбинации",
    "warnings": {
      "200": "⚠ Максимальная доза"
    }
  },
  "bupropion": {
    "id": "bupropion",
    "brand_name": "Wellbutrin",
    "generic_name": "bupropion",
    "drug_class": "other",
    "indications": [],
    "bindings": [
      {
        "receptor": "DAT",
        "ki_nM": 526,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "NET",
        "ki_nM": 2170,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#fbbf24",
    "region_targets": [
      "dlPFC",
      "nac",
      "lc",
      "brainstem"
    ],
    "legacy_short": "БУПРО",
    "legacy_name_ru": "Бупропион",
    "doses": [
      75,
      150,
      225,
      300,
      450
    ],
    "default_dose": 225,
    "dose_unit": "мг",
    "warn_dose": 300,
    "max_dose": 450,
    "warn_text": "Судорожный риск дозозависим",
    "warnings": {
      "300": "⚠ >300мг: повышенный риск судорог (FDA)",
      "450": "⛔ Максимальная одобренная доза"
    },
    "cyp_inhibits": [
      {
        "enzyme": "CYP2D6",
        "strength": "moderate"
      }
    ]
  },
  "atomoxetine": {
    "id": "atomoxetine",
    "brand_name": "Strattera",
    "generic_name": "atomoxetine",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 5,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 77,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "DAT",
        "ki_nM": 1451,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#34d399",
    "region_targets": [
      "dlPFC",
      "vmPFC",
      "acc",
      "insula",
      "parietal",
      "lc",
      "cerebellum",
      "brainstem",
      "spinal"
    ],
    "legacy_short": "АТОМ",
    "legacy_name_ru": "Атомоксетин",
    "doses": [
      5,
      10,
      18,
      25,
      40,
      60,
      80
    ],
    "default_dose": 10,
    "dose_unit": "мг",
    "warn_dose": 60,
    "max_dose": 80,
    "warn_text": "Гепатотоксичность — контроль печени",
    "warnings": {
      "60": "⚠ Высокая доза — контроль печени",
      "80": "⛔ Максимальная доза"
    }
  },
  "vortioxetine": {
    "id": "vortioxetine",
    "brand_name": "Brintellix",
    "generic_name": "vortioxetine",
    "drug_class": "SSRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "SERT",
        "ki_nM": 1.6,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "5HT3",
        "ki_nM": 3.7,
        "type": "antagonist"
      },
      {
        "receptor": "5HT1A",
        "ki_nM": 15,
        "type": "agonist"
      },
      {
        "receptor": "5HT7",
        "ki_nM": 19,
        "type": "antagonist"
      },
      {
        "receptor": "5HT1B",
        "ki_nM": 33,
        "type": "antagonist"
      },
      {
        "receptor": "s1",
        "ki_nM": 286,
        "type": "agonist",
        "source": "Sanchez et al. 2015"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#a78bfa",
    "region_targets": [
      "dlPFC",
      "acc",
      "amygdala",
      "hippo",
      "vta",
      "raphe"
    ],
    "legacy_short": "ВОРТ",
    "legacy_name_ru": "Вортиоксетин",
    "doses": [
      5,
      10,
      15,
      20
    ],
    "default_dose": 10,
    "dose_unit": "мг"
  },
  "pramipexole": {
    "id": "pramipexole",
    "brand_name": "Mirapex",
    "generic_name": "pramipexole",
    "drug_class": "dopamine agonist",
    "indications": [],
    "bindings": [
      {
        "receptor": "D3",
        "ki_nM": 0.5,
        "type": "agonist",
        "intrinsic_efficacy": 1,
        "source": "Piercey et al. 1996"
      },
      {
        "receptor": "D2",
        "ki_nM": 3.9,
        "type": "agonist",
        "intrinsic_efficacy": 0.9,
        "source": "Piercey et al. 1996"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#f87171",
    "region_targets": [
      "nac",
      "vta"
    ],
    "legacy_short": "ПРАМ",
    "legacy_name_ru": "Прамипексол",
    "doses": [
      0.0625,
      0.125,
      0.25,
      0.5,
      0.75,
      1,
      1.5
    ],
    "default_dose": 0.125,
    "dose_unit": "мг",
    "warn_dose": 1,
    "max_dose": 1.5,
    "warn_text": "Импульсный контроль — мониторинг",
    "warnings": {
      "1": "⚠ Риск нарушений импульсного контроля",
      "1.5": "⛔ Максимальная доза"
    }
  },
  "duloxetine": {
    "id": "duloxetine",
    "brand_name": "Cymbalta",
    "generic_name": "duloxetine",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "SERT",
        "ki_nM": 0.8,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "NET",
        "ki_nM": 7.5,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "DAT",
        "ki_nM": 240,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#22d3ee",
    "region_targets": [
      "dlPFC",
      "insula",
      "brainstem",
      "spinal",
      "lc",
      "amygdala",
      "vta"
    ],
    "legacy_short": "ДУЛО",
    "legacy_name_ru": "Дулоксетин",
    "doses": [
      20,
      30,
      60,
      90,
      120
    ],
    "default_dose": 30,
    "dose_unit": "мг",
    "warn_dose": 90,
    "max_dose": 120,
    "warn_text": "Гепатотоксичность при высоких дозах",
    "warnings": {
      "90": "⚠ Высокая доза",
      "120": "⛔ Максимальная доза"
    }
  },
  "cariprazine": {
    "id": "cariprazine",
    "brand_name": "Vraylar",
    "generic_name": "cariprazine",
    "drug_class": "atypical antipsychotic (partial agonist)",
    "indications": [],
    "bindings": [
      {
        "receptor": "5HT1A",
        "ki_nM": 2.6,
        "type": "agonist"
      },
      {
        "receptor": "D2",
        "ki_nM": 0.49,
        "type": "partial_agonist",
        "intrinsic_efficacy": 0.25,
        "source": "Kiss et al. 2010"
      },
      {
        "receptor": "D3",
        "ki_nM": 0.085,
        "type": "partial_agonist",
        "intrinsic_efficacy": 0.4,
        "source": "Kiss et al. 2010"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#fb923c",
    "region_targets": [
      "nac",
      "vta"
    ],
    "legacy_short": "КАРИ",
    "legacy_name_ru": "Карипразин",
    "doses": [
      0.5,
      1,
      1.5,
      3,
      4.5,
      6
    ],
    "default_dose": 1.5,
    "dose_unit": "мг"
  },
  "dhea": {
    "id": "dhea",
    "brand_name": "DHEA",
    "generic_name": "dhea",
    "drug_class": "neurosteroid",
    "indications": [],
    "bindings": [
      {
        "receptor": "s1",
        "ki_nM": 706,
        "type": "agonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#f472b6",
    "region_targets": [
      "hippo",
      "dlPFC",
      "amygdala"
    ],
    "legacy_short": "DHEA",
    "legacy_name_ru": "DHEA",
    "doses": [
      25,
      50,
      100
    ],
    "default_dose": 50,
    "dose_unit": "мг"
  },
  "escitalopram": {
    "id": "escitalopram",
    "brand_name": "Lexapro",
    "generic_name": "escitalopram",
    "drug_class": "SSRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "SERT",
        "ki_nM": 1.1,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "s1",
        "ki_nM": 288,
        "type": "agonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#38bdf8",
    "region_targets": [
      "dlPFC",
      "amygdala",
      "hippo",
      "raphe",
      "vta"
    ],
    "legacy_short": "ЭСЦИ",
    "legacy_name_ru": "Эсциталопрам",
    "doses": [
      5,
      10,
      15,
      20
    ],
    "default_dose": 10,
    "dose_unit": "мг"
  },
  "fluvoxamine": {
    "id": "fluvoxamine",
    "brand_name": "Luvox",
    "generic_name": "fluvoxamine",
    "drug_class": "SSRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "SERT",
        "ki_nM": 2,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "s1",
        "ki_nM": 17,
        "type": "agonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#4ade80",
    "region_targets": [
      "dlPFC",
      "hippo",
      "amygdala"
    ],
    "legacy_short": "ФЛУВ",
    "legacy_name_ru": "Флувоксамин",
    "doses": [
      25,
      50,
      100,
      200,
      300
    ],
    "default_dose": 50,
    "dose_unit": "мг"
  },
  "guanfacine": {
    "id": "guanfacine",
    "brand_name": "Intuniv",
    "generic_name": "guanfacine",
    "drug_class": "alpha-2A agonist",
    "indications": [],
    "bindings": [
      {
        "receptor": "alpha2A",
        "ki_nM": 1.9,
        "type": "agonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#2dd4bf",
    "region_targets": [
      "dlPFC",
      "parietal",
      "lc",
      "amygdala"
    ],
    "legacy_short": "ГУАН",
    "legacy_name_ru": "Гуанфацин",
    "doses": [
      0.5,
      1,
      2,
      3,
      4
    ],
    "default_dose": 1,
    "dose_unit": "мг"
  },
  "lamotrigine": {
    "id": "lamotrigine",
    "brand_name": "Lamictal",
    "generic_name": "lamotrigine",
    "drug_class": "anticonvulsant (glutamate modulator)",
    "indications": [],
    "bindings": [
      {
        "receptor": "presynapticGluRelease",
        "ki_nM": 0,
        "type": "modulator",
        "source": "Xie & Bhatt 2005, via Nav"
      },
      {
        "receptor": "Nav",
        "ki_nM": 0,
        "type": "modulator",
        "source": "Cheung et al. 1992"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#e879f9",
    "region_targets": [
      "dlPFC",
      "hippo",
      "amygdala"
    ],
    "legacy_short": "ЛАМО",
    "legacy_name_ru": "Ламотриджин",
    "doses": [
      12.5,
      25,
      50,
      100,
      200,
      400
    ],
    "default_dose": 25,
    "dose_unit": "мг",
    "warn_dose": 200,
    "max_dose": 400,
    "warn_text": "SJS-риск при быстрой титрации",
    "warnings": {
      "200": "⚠ Титровать медленно — SJS-риск",
      "400": "⛔ Максимальная доза"
    }
  },
  "nac_supp": {
    "id": "nac_supp",
    "brand_name": "NAC",
    "generic_name": "nac supp",
    "drug_class": "amino acid derivative (antioxidant)",
    "indications": [],
    "bindings": [
      {
        "receptor": "cystineGlutamateAntiporter",
        "ki_nM": 0,
        "type": "modulator",
        "source": "Baker et al. 2003, system Xc-"
      },
      {
        "receptor": "mGluR2",
        "ki_nM": 0,
        "type": "modulator",
        "source": "indirect via xCT→extrasynaptic Glu↓→mGluR2/3"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#a3e635",
    "region_targets": [
      "dlPFC",
      "nac",
      "hippo"
    ],
    "legacy_short": "NAC",
    "legacy_name_ru": "NAC",
    "doses": [
      300,
      600,
      1200,
      1800,
      2400
    ],
    "default_dose": 600,
    "dose_unit": "мг"
  },
  "desipramine": {
    "id": "desipramine",
    "brand_name": "Norpramin",
    "generic_name": "desipramine",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 0.83,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 17.6,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "H1",
        "ki_nM": 60,
        "type": "antagonist"
      },
      {
        "receptor": "alpha1",
        "ki_nM": 100,
        "type": "antagonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#f97316",
    "region_targets": [
      "dlPFC",
      "insula",
      "acc",
      "vmPFC",
      "lc",
      "brainstem",
      "spinal"
    ],
    "legacy_short": "ДЕЗИ",
    "legacy_name_ru": "Дезипрамин",
    "doses": [
      10,
      25,
      50,
      75,
      100,
      150,
      200,
      300
    ],
    "default_dose": 50,
    "dose_unit": "мг",
    "warn_dose": 150,
    "max_dose": 300,
    "warn_text": "Кардиотоксичность — ЭКГ обязательно",
    "warnings": {
      "150": "⚠ Высокая доза — ЭКГ мониторинг",
      "300": "⛔ Максимальная доза — кардиотоксичность"
    },
    "cyp_metabolized_by": [
      "CYP2D6"
    ]
  },
  "nortriptyline": {
    "id": "nortriptyline",
    "brand_name": "Pamelor",
    "generic_name": "nortriptyline",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 1.49,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 16.5,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "H1",
        "ki_nM": 10,
        "type": "antagonist"
      },
      {
        "receptor": "alpha1",
        "ki_nM": 55,
        "type": "antagonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#fb923c",
    "region_targets": [
      "dlPFC",
      "insula",
      "amygdala",
      "lc",
      "brainstem",
      "spinal"
    ],
    "legacy_short": "НОРТ",
    "legacy_name_ru": "Нортриптилин",
    "doses": [
      10,
      25,
      50,
      75,
      100,
      150
    ],
    "default_dose": 25,
    "dose_unit": "мг",
    "cyp_metabolized_by": [
      "CYP2D6"
    ]
  },
  "protriptyline": {
    "id": "protriptyline",
    "brand_name": "Vivactil",
    "generic_name": "protriptyline",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 1.4,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 19.6,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#d97706",
    "region_targets": [
      "dlPFC",
      "insula",
      "lc",
      "brainstem"
    ],
    "legacy_short": "ПРОТ",
    "legacy_name_ru": "Протриптилин",
    "doses": [
      5,
      10,
      15,
      20,
      30,
      40,
      60
    ],
    "default_dose": 10,
    "dose_unit": "мг",
    "cyp_metabolized_by": [
      "CYP2D6"
    ]
  },
  "reboxetine": {
    "id": "reboxetine",
    "brand_name": "Edronax",
    "generic_name": "reboxetine",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 3,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 242,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#06b6d4",
    "region_targets": [
      "dlPFC",
      "insula",
      "vmPFC",
      "acc",
      "lc"
    ],
    "legacy_short": "РЕБО",
    "legacy_name_ru": "Ребоксетин",
    "doses": [
      2,
      4,
      6,
      8,
      10,
      12
    ],
    "default_dose": 4,
    "dose_unit": "мг"
  },
  "amitriptyline": {
    "id": "amitriptyline",
    "brand_name": "Elavil",
    "generic_name": "amitriptyline",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 13.3,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 3.13,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "H1",
        "ki_nM": 1,
        "type": "antagonist"
      },
      {
        "receptor": "alpha1",
        "ki_nM": 24,
        "type": "antagonist"
      },
      {
        "receptor": "s1",
        "ki_nM": 196,
        "type": "agonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#eab308",
    "region_targets": [
      "amygdala",
      "hippo",
      "dlPFC",
      "brainstem",
      "spinal",
      "raphe"
    ],
    "legacy_short": "АМИТ",
    "legacy_name_ru": "Амитриптилин",
    "doses": [
      10,
      25,
      50,
      75,
      100,
      150,
      200,
      300
    ],
    "default_dose": 25,
    "dose_unit": "мг",
    "cyp_metabolized_by": [
      "CYP2D6"
    ]
  },
  "milnacipran": {
    "id": "milnacipran",
    "brand_name": "Savella",
    "generic_name": "milnacipran",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 22,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 8.4,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#0891b2",
    "region_targets": [
      "dlPFC",
      "spinal",
      "insula",
      "brainstem",
      "lc"
    ],
    "legacy_short": "МИЛН",
    "legacy_name_ru": "Милнаципран",
    "doses": [
      12.5,
      25,
      50,
      100,
      200
    ],
    "default_dose": 50,
    "dose_unit": "мг"
  },
  "levomilnacipran": {
    "id": "levomilnacipran",
    "brand_name": "Fetzima",
    "generic_name": "levomilnacipran",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 92.2,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 11.2,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#0284c7",
    "region_targets": [
      "dlPFC",
      "insula",
      "spinal",
      "brainstem",
      "lc"
    ],
    "legacy_short": "ЛЕВО",
    "legacy_name_ru": "Левомилнаципран",
    "doses": [
      20,
      40,
      80,
      120
    ],
    "default_dose": 40,
    "dose_unit": "мг"
  },
  "venlafaxine": {
    "id": "venlafaxine",
    "brand_name": "Effexor",
    "generic_name": "venlafaxine",
    "drug_class": "SNRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 538,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 7.8,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#0369a1",
    "region_targets": [
      "amygdala",
      "dlPFC",
      "hippo",
      "raphe",
      "brainstem",
      "spinal",
      "vta"
    ],
    "legacy_short": "ВЕНЛ",
    "legacy_name_ru": "Венлафаксин",
    "doses": [
      37.5,
      75,
      150,
      225,
      300,
      375
    ],
    "default_dose": 75,
    "dose_unit": "мг",
    "warn_dose": 225,
    "max_dose": 375,
    "warn_text": "Рост АД при высоких дозах",
    "warnings": {
      "225": "⚠ >225мг: рост АД — мониторинг",
      "375": "⛔ Максимальная доза"
    },
    "cyp_metabolized_by": [
      "CYP2D6"
    ]
  },
  "desvenlafaxine": {
    "id": "desvenlafaxine",
    "brand_name": "Pristiq",
    "generic_name": "desvenlafaxine",
    "drug_class": "other",
    "indications": [],
    "bindings": [
      {
        "receptor": "NET",
        "ki_nM": 558.4,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "SERT",
        "ki_nM": 40.2,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#1d4ed8",
    "region_targets": [
      "amygdala",
      "dlPFC",
      "raphe",
      "brainstem",
      "spinal"
    ],
    "legacy_short": "ДЕСВ",
    "legacy_name_ru": "Десвенлафаксин",
    "doses": [
      25,
      50,
      100
    ],
    "default_dose": 50,
    "dose_unit": "мг"
  },
  "quetiapine": {
    "id": "quetiapine",
    "brand_name": "Seroquel",
    "generic_name": "quetiapine",
    "drug_class": "atypical antipsychotic",
    "indications": [],
    "bindings": [
      {
        "receptor": "H1",
        "ki_nM": 11,
        "type": "antagonist"
      },
      {
        "receptor": "alpha1",
        "ki_nM": 7,
        "type": "antagonist"
      },
      {
        "receptor": "D2",
        "ki_nM": 770,
        "type": "antagonist"
      },
      {
        "receptor": "5HT2C",
        "ki_nM": 615,
        "type": "antagonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#7c3aed",
    "region_targets": [
      "dlPFC",
      "amygdala",
      "lc",
      "brainstem"
    ],
    "legacy_short": "КВЕТ",
    "legacy_name_ru": "Кветиапин",
    "doses": [
      25,
      50,
      100,
      200,
      300,
      400,
      600,
      800
    ],
    "default_dose": 50,
    "dose_unit": "мг"
  },
  "opipramol": {
    "id": "opipramol",
    "brand_name": "Insidon",
    "generic_name": "opipramol",
    "drug_class": "σ1 agonist (tricyclic structure)",
    "indications": [],
    "bindings": [
      {
        "receptor": "s1",
        "ki_nM": 50,
        "type": "agonist",
        "source": "Muller et al. 2004 (corrected from erroneous 0.2 nM)"
      },
      {
        "receptor": "H1",
        "ki_nM": 6,
        "type": "antagonist"
      },
      {
        "receptor": "D2",
        "ki_nM": 120,
        "type": "antagonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#d946ef",
    "region_targets": [
      "hippo",
      "dlPFC",
      "amygdala"
    ],
    "legacy_short": "ОПИП",
    "legacy_name_ru": "Опипрамол",
    "doses": [
      50,
      100,
      150,
      200
    ],
    "default_dose": 100,
    "dose_unit": "мг"
  },
  "donepezil": {
    "id": "donepezil",
    "brand_name": "Aricept",
    "generic_name": "donepezil",
    "drug_class": "cholinesterase inhibitor",
    "indications": [],
    "bindings": [
      {
        "receptor": "s1",
        "ki_nM": 14.6,
        "type": "agonist",
        "source": "Maurice & Lockhart 1997, PMID:9233505"
      },
      {
        "receptor": "AChE",
        "ki_nM": 6.7,
        "type": "inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#ec4899",
    "region_targets": [
      "hippo",
      "dlPFC",
      "nac"
    ],
    "legacy_short": "ДОНЕ",
    "legacy_name_ru": "Донепезил",
    "doses": [
      5,
      10,
      23
    ],
    "default_dose": 5,
    "dose_unit": "мг"
  },
  "dextromethorphan": {
    "id": "dextromethorphan",
    "brand_name": "DXM",
    "generic_name": "dextromethorphan",
    "drug_class": "NMDA antagonist / σ1 agonist",
    "indications": [],
    "bindings": [
      {
        "receptor": "s1",
        "ki_nM": 142,
        "type": "agonist"
      },
      {
        "receptor": "SERT",
        "ki_nM": 23,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "NET",
        "ki_nM": 240,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "NMDA",
        "ki_nM": 500,
        "type": "antagonist"
      },
      {
        "receptor": "GluN2B",
        "ki_nM": 680,
        "type": "antagonist",
        "source": "Bhatt et al. 2017"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#a855f7",
    "region_targets": [
      "hippo",
      "dlPFC",
      "raphe"
    ],
    "legacy_short": "DXM",
    "legacy_name_ru": "Декстрометорфан",
    "doses": [
      15,
      30,
      45,
      60
    ],
    "default_dose": 30,
    "dose_unit": "мг"
  },
  "auvelity": {
    "id": "auvelity",
    "brand_name": "Auvelity",
    "generic_name": "auvelity",
    "drug_class": "NMDA antagonist / NDRI combination",
    "indications": [],
    "bindings": [
      {
        "receptor": "s1",
        "ki_nM": 142,
        "type": "agonist"
      },
      {
        "receptor": "NMDA",
        "ki_nM": 500,
        "type": "antagonist"
      },
      {
        "receptor": "DAT",
        "ki_nM": 500,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#8b5cf6",
    "region_targets": [
      "hippo",
      "dlPFC",
      "nac"
    ],
    "legacy_short": "АУВЛ",
    "legacy_name_ru": "Auvelity (DXM/бупро)",
    "doses": [
      1
    ],
    "default_dose": 1,
    "dose_unit": "таб"
  },
  "fluoxetine": {
    "id": "fluoxetine",
    "brand_name": "Prozac",
    "generic_name": "fluoxetine",
    "drug_class": "SSRI",
    "indications": [],
    "bindings": [
      {
        "receptor": "SERT",
        "ki_nM": 0.8,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "s1",
        "ki_nM": 191,
        "type": "agonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#0ea5e9",
    "region_targets": [
      "amygdala",
      "hippo",
      "dlPFC",
      "raphe",
      "vta",
      "nac"
    ],
    "legacy_short": "ФЛУО",
    "legacy_name_ru": "Флуоксетин",
    "doses": [
      10,
      20,
      40,
      60,
      80
    ],
    "default_dose": 20,
    "dose_unit": "мг",
    "cyp_inhibits": [
      {
        "enzyme": "CYP2D6",
        "strength": "strong"
      }
    ]
  },
  "pregnenolone": {
    "id": "pregnenolone",
    "brand_name": "Pregnenolone",
    "generic_name": "pregnenolone",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [
      {
        "receptor": "s1",
        "ki_nM": 3196,
        "type": "agonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#f9a8d4",
    "region_targets": [
      "hippo",
      "dlPFC"
    ],
    "legacy_short": "ПРЕГ",
    "legacy_name_ru": "Прегненолон",
    "doses": [
      10,
      25,
      50,
      100,
      200,
      400,
      500
    ],
    "default_dose": 50,
    "dose_unit": "мг",
    "is_otc": true
  },
  "ifenprodil": {
    "id": "ifenprodil",
    "brand_name": "Ifenprodil",
    "generic_name": "ifenprodil",
    "drug_class": "GluN2B / σ1 ligand",
    "indications": [],
    "bindings": [
      {
        "receptor": "s1",
        "ki_nM": 2,
        "type": "agonist"
      },
      {
        "receptor": "NMDA",
        "ki_nM": 50,
        "type": "antagonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#c084fc",
    "region_targets": [
      "hippo",
      "dlPFC",
      "amygdala"
    ],
    "legacy_short": "ИФЕН",
    "legacy_name_ru": "Ифенпродил",
    "doses": [
      20,
      40,
      60
    ],
    "default_dose": 40,
    "dose_unit": "мг"
  },
  "ketamine": {
    "id": "ketamine",
    "brand_name": "Ketalar",
    "generic_name": "ketamine",
    "drug_class": "NMDA antagonist (dissociative)",
    "indications": [],
    "bindings": [
      {
        "receptor": "NMDA",
        "ki_nM": 10,
        "type": "antagonist"
      },
      {
        "receptor": "s1",
        "ki_nM": 130,
        "type": "agonist",
        "source": "Robson et al. 2012"
      },
      {
        "receptor": "mu",
        "ki_nM": 25000,
        "type": "agonist",
        "source": "Hirota et al. 1999, weak"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#f43f5e",
    "region_targets": [
      "hippo",
      "dlPFC",
      "amygdala"
    ],
    "legacy_short": "КЕТА",
    "legacy_name_ru": "Кетамин",
    "doses": [
      0.5
    ],
    "default_dose": 0.5,
    "dose_unit": "мг/кг"
  },
  "progesterone": {
    "id": "progesterone",
    "brand_name": "Prometrium",
    "generic_name": "progesterone",
    "drug_class": "neurosteroid",
    "indications": [],
    "bindings": [
      {
        "receptor": "s1",
        "ki_nM": 36,
        "type": "antagonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#be185d",
    "region_targets": [
      "hippo",
      "dlPFC"
    ],
    "legacy_short": "ПРОГ",
    "legacy_name_ru": "Прогестерон",
    "doses": [
      100,
      200,
      300
    ],
    "default_dose": 100,
    "dose_unit": "мг"
  },
  "aripiprazole": {
    "id": "aripiprazole",
    "brand_name": "Abilify",
    "generic_name": "aripiprazole",
    "drug_class": "atypical antipsychotic (partial agonist)",
    "indications": [],
    "bindings": [
      {
        "receptor": "D3",
        "ki_nM": 0.8,
        "type": "antagonist"
      },
      {
        "receptor": "5HT2C",
        "ki_nM": 15,
        "type": "antagonist"
      },
      {
        "receptor": "D2",
        "ki_nM": 0.34,
        "type": "partial_agonist",
        "intrinsic_efficacy": 0.3,
        "source": "Burris et al. 2002"
      },
      {
        "receptor": "5HT1A",
        "ki_nM": 1.7,
        "type": "partial_agonist",
        "intrinsic_efficacy": 0.5,
        "source": "Jordan et al. 2002"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#dc2626",
    "region_targets": [
      "nac",
      "vta",
      "dlPFC",
      "amygdala"
    ],
    "legacy_short": "АРИП",
    "legacy_name_ru": "Арипипразол",
    "doses": [
      2,
      5,
      10,
      15,
      20,
      30
    ],
    "default_dose": 5,
    "dose_unit": "мг",
    "cyp_metabolized_by": [
      "CYP2D6"
    ]
  },
  "brexpiprazole": {
    "id": "brexpiprazole",
    "brand_name": "Rexulti",
    "generic_name": "brexpiprazole",
    "drug_class": "atypical antipsychotic (partial agonist)",
    "indications": [],
    "bindings": [
      {
        "receptor": "D3",
        "ki_nM": 1.1,
        "type": "antagonist"
      },
      {
        "receptor": "alpha1",
        "ki_nM": 3.8,
        "type": "antagonist"
      },
      {
        "receptor": "D2",
        "ki_nM": 0.3,
        "type": "partial_agonist",
        "intrinsic_efficacy": 0.35,
        "source": "Maeda et al. 2014"
      },
      {
        "receptor": "5HT1A",
        "ki_nM": 0.12,
        "type": "partial_agonist",
        "intrinsic_efficacy": 0.5,
        "source": "Maeda et al. 2014"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#e11d48",
    "region_targets": [
      "nac",
      "vta",
      "amygdala",
      "lc"
    ],
    "legacy_short": "БРЕК",
    "legacy_name_ru": "Брексипразол",
    "doses": [
      0.25,
      0.5,
      1,
      2,
      3,
      4
    ],
    "default_dose": 1,
    "dose_unit": "мг",
    "cyp_metabolized_by": [
      "CYP2D6"
    ]
  },
  "methylphenidate": {
    "id": "methylphenidate",
    "brand_name": "Ritalin",
    "generic_name": "methylphenidate",
    "drug_class": "psychostimulant",
    "indications": [],
    "bindings": [
      {
        "receptor": "DAT",
        "ki_nM": 34,
        "type": "reuptake_inhibitor"
      },
      {
        "receptor": "NET",
        "ki_nM": 339,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#b45309",
    "region_targets": [
      "nac",
      "dlPFC",
      "vta"
    ],
    "legacy_short": "МФД",
    "legacy_name_ru": "Метилфенидат",
    "doses": [
      5,
      10,
      18,
      20,
      27,
      36,
      54
    ],
    "default_dose": 10,
    "dose_unit": "мг"
  },
  "lisdexamfetamine": {
    "id": "lisdexamfetamine",
    "brand_name": "Vyvanse",
    "generic_name": "lisdexamfetamine",
    "drug_class": "psychostimulant",
    "indications": [],
    "bindings": [
      {
        "receptor": "DAT",
        "ki_nM": 1,
        "type": "releaser"
      },
      {
        "receptor": "NET",
        "ki_nM": 1,
        "type": "releaser"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#ca8a04",
    "region_targets": [
      "nac",
      "dlPFC",
      "vta",
      "lc"
    ],
    "legacy_short": "ЛИСД",
    "legacy_name_ru": "Лисдексамфетамин",
    "doses": [
      20,
      30,
      40,
      50,
      60,
      70
    ],
    "default_dose": 30,
    "dose_unit": "мг"
  },
  "modafinil": {
    "id": "modafinil",
    "brand_name": "Provigil",
    "generic_name": "modafinil",
    "drug_class": "wakefulness-promoting agent",
    "indications": [],
    "bindings": [
      {
        "receptor": "DAT",
        "ki_nM": 2000,
        "type": "reuptake_inhibitor"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#84cc16",
    "region_targets": [
      "dlPFC",
      "nac"
    ],
    "legacy_short": "МОДА",
    "legacy_name_ru": "Модафинил",
    "doses": [
      100,
      200,
      400
    ],
    "default_dose": 200,
    "dose_unit": "мг"
  },
  "selegiline_oral": {
    "id": "selegiline_oral",
    "brand_name": "Emsam",
    "generic_name": "selegiline oral",
    "drug_class": "MAO-B inhibitor",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#65a30d",
    "region_targets": [
      "nac",
      "dlPFC",
      "vta"
    ],
    "legacy_short": "СЕЛЕ",
    "legacy_name_ru": "Селегилин",
    "doses": [
      2.5,
      5,
      10
    ],
    "default_dose": 5,
    "dose_unit": "мг"
  },
  "amisulpride_low": {
    "id": "amisulpride_low",
    "brand_name": "Solian",
    "generic_name": "amisulpride low",
    "drug_class": "atypical antipsychotic",
    "indications": [],
    "bindings": [
      {
        "receptor": "D2",
        "ki_nM": 2.8,
        "type": "antagonist"
      },
      {
        "receptor": "D3",
        "ki_nM": 3.2,
        "type": "antagonist"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#fb7185",
    "region_targets": [
      "nac",
      "vta"
    ],
    "legacy_short": "АМИС",
    "legacy_name_ru": "Амисульприд",
    "doses": [
      12.5,
      25,
      50,
      100
    ],
    "default_dose": 50,
    "dose_unit": "мг"
  },
  "levodopa": {
    "id": "levodopa",
    "brand_name": "Sinemet",
    "generic_name": "levodopa",
    "drug_class": "dopamine precursor",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#16a34a",
    "region_targets": [
      "nac",
      "dlPFC",
      "vta"
    ],
    "legacy_short": "ЛДОП",
    "legacy_name_ru": "L-DOPA",
    "doses": [
      50,
      100,
      250,
      500
    ],
    "default_dose": 100,
    "dose_unit": "мг"
  },
  "same": {
    "id": "same",
    "brand_name": "SAMe",
    "generic_name": "same",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#86efac",
    "region_targets": [
      "dlPFC",
      "hippo"
    ],
    "legacy_short": "SAMe",
    "legacy_name_ru": "SAMe",
    "doses": [
      200,
      400,
      800,
      1200,
      1600
    ],
    "default_dose": 400,
    "dose_unit": "мг",
    "is_otc": true
  },
  "omega3": {
    "id": "omega3",
    "brand_name": "Omega-3",
    "generic_name": "omega3",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#a7f3d0",
    "region_targets": [
      "hippo",
      "dlPFC"
    ],
    "legacy_short": "ОМ3",
    "legacy_name_ru": "Омега-3 EPA/DHA",
    "doses": [
      500,
      1000,
      2000,
      3000,
      4000
    ],
    "default_dose": 2000,
    "dose_unit": "мг",
    "is_otc": true
  },
  "rhodiola": {
    "id": "rhodiola",
    "brand_name": "Rhodiola",
    "generic_name": "rhodiola",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#d8b4fe",
    "region_targets": [
      "dlPFC"
    ],
    "legacy_short": "РОДО",
    "legacy_name_ru": "Родиола",
    "doses": [
      100,
      200,
      400,
      600
    ],
    "default_dose": 200,
    "dose_unit": "мг",
    "is_otc": true
  },
  "curcumin": {
    "id": "curcumin",
    "brand_name": "Curcumin",
    "generic_name": "curcumin",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#c4b5fd",
    "region_targets": [
      "hippo"
    ],
    "legacy_short": "КУРК",
    "legacy_name_ru": "Куркумин",
    "doses": [
      250,
      500,
      1000
    ],
    "default_dose": 500,
    "dose_unit": "мг",
    "is_otc": true
  },
  "b_vitamins": {
    "id": "b_vitamins",
    "brand_name": "B-Complex",
    "generic_name": "b vitamins",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#bef264",
    "region_targets": [
      "dlPFC"
    ],
    "legacy_short": "BВИТ",
    "legacy_name_ru": "B-вит/L-метилфолат",
    "doses": [
      1
    ],
    "default_dose": 1,
    "dose_unit": "комп",
    "is_otc": true
  },
  "l_tyrosine": {
    "id": "l_tyrosine",
    "brand_name": "L-Tyrosine",
    "generic_name": "l tyrosine",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#d9f99d",
    "region_targets": [
      "dlPFC"
    ],
    "legacy_short": "ТИРО",
    "legacy_name_ru": "L-тирозин",
    "doses": [
      250,
      500,
      1000,
      2000
    ],
    "default_dose": 500,
    "dose_unit": "мг",
    "is_otc": true
  },
  "lions_mane": {
    "id": "lions_mane",
    "brand_name": "Lion's Mane",
    "generic_name": "lions mane",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#fde68a",
    "region_targets": [
      "hippo"
    ],
    "legacy_short": "ЕЖОВ",
    "legacy_name_ru": "Ежовик гребенчатый",
    "doses": [
      250,
      500,
      1000,
      2000,
      3000
    ],
    "default_dose": 1000,
    "dose_unit": "мг",
    "is_otc": true
  },
  "magnesium_threonate": {
    "id": "magnesium_threonate",
    "brand_name": "Magtein",
    "generic_name": "magnesium threonate",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#99f6e4",
    "region_targets": [
      "hippo"
    ],
    "legacy_short": "MgTr",
    "legacy_name_ru": "Магний L-треонат",
    "doses": [
      500,
      1000,
      1500,
      2000
    ],
    "default_dose": 1000,
    "dose_unit": "мг",
    "is_otc": true
  },
  "pea_um": {
    "id": "pea_um",
    "brand_name": "PEA",
    "generic_name": "pea um",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#fecaca",
    "region_targets": [
      "vta"
    ],
    "legacy_short": "PEA",
    "legacy_name_ru": "PEA ультрамикрониз.",
    "doses": [
      300,
      600,
      900,
      1200
    ],
    "default_dose": 600,
    "dose_unit": "мг",
    "is_otc": true
  },
  "mucuna": {
    "id": "mucuna",
    "brand_name": "Mucuna",
    "generic_name": "mucuna",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#bbf7d0",
    "region_targets": [
      "nac"
    ],
    "legacy_short": "МУКУ",
    "legacy_name_ru": "Мукуна жгучая",
    "doses": [
      2500,
      5000
    ],
    "default_dose": 2500,
    "dose_unit": "мг",
    "is_otc": true
  },
  "vitamin_d": {
    "id": "vitamin_d",
    "brand_name": "Vitamin D",
    "generic_name": "vitamin d",
    "drug_class": "supplement",
    "indications": [],
    "bindings": [],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#fef08a",
    "region_targets": [],
    "legacy_short": "ВитD",
    "legacy_name_ru": "Витамин D3",
    "doses": [
      1000,
      2000,
      4000,
      5000,
      10000
    ],
    "default_dose": 2000,
    "dose_unit": "МЕ",
    "is_otc": true
  },
  "memantine": {
    "id": "memantine",
    "brand_name": "Namenda",
    "generic_name": "memantine",
    "drug_class": "NMDA antagonist (uncompetitive)",
    "indications": [
      "Alzheimer's disease",
      "off-label: depression augmentation"
    ],
    "bindings": [
      {
        "receptor": "NMDA",
        "ki_nM": 500,
        "type": "antagonist",
        "source": "Parsons et al. 1999, uncompetitive"
      },
      {
        "receptor": "5HT3",
        "ki_nM": 2400,
        "type": "antagonist",
        "source": "Rammes et al. 2001"
      },
      {
        "receptor": "s1",
        "ki_nM": 2600,
        "type": "agonist",
        "source": "Nguyen et al. 2014, weak"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#e879f9",
    "region_targets": [
      "hippo",
      "dlPFC",
      "amygdala"
    ],
    "legacy_short": "МЕМА",
    "legacy_name_ru": "Мемантин",
    "doses": [
      5,
      10,
      20,
      28
    ],
    "default_dose": 10,
    "dose_unit": "мг",
    "max_dose": 28
  },
  "topiramate": {
    "id": "topiramate",
    "brand_name": "Topamax",
    "generic_name": "topiramate",
    "drug_class": "anticonvulsant (AMPA antagonist / GABAa modulator)",
    "indications": [
      "epilepsy",
      "migraine prophylaxis",
      "off-label: PTSD"
    ],
    "bindings": [
      {
        "receptor": "AMPA",
        "ki_nM": 0,
        "type": "antagonist",
        "source": "Gibbs et al. 2000"
      },
      {
        "receptor": "kainate",
        "ki_nM": 0,
        "type": "antagonist",
        "source": "Gibbs et al. 2000"
      },
      {
        "receptor": "GABAa",
        "ki_nM": 0,
        "type": "modulator",
        "source": "White et al. 1997, positive allosteric"
      },
      {
        "receptor": "Nav",
        "ki_nM": 0,
        "type": "modulator",
        "source": "Zona & Bhatt 2001"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#c084fc",
    "region_targets": [
      "dlPFC",
      "hippo",
      "amygdala"
    ],
    "legacy_short": "ТОПИ",
    "legacy_name_ru": "Топирамат",
    "doses": [
      25,
      50,
      100,
      200,
      400
    ],
    "default_dose": 50,
    "dose_unit": "мг",
    "max_dose": 400
  },
  "riluzole": {
    "id": "riluzole",
    "brand_name": "Rilutek",
    "generic_name": "riluzole",
    "drug_class": "glutamate modulator (uptake enhancer)",
    "indications": [
      "ALS",
      "off-label: OCD augmentation, depression"
    ],
    "bindings": [
      {
        "receptor": "glutamateUptake",
        "ki_nM": 0,
        "type": "modulator",
        "source": "Doble 1996, enhances EAAT2"
      },
      {
        "receptor": "Nav",
        "ki_nM": 0,
        "type": "modulator",
        "source": "Song et al. 1997"
      },
      {
        "receptor": "NMDA",
        "ki_nM": 0,
        "type": "antagonist",
        "source": "Bhatt et al. 2010, weak/indirect"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#818cf8",
    "region_targets": [
      "dlPFC",
      "hippo",
      "brainstem",
      "spinal"
    ],
    "legacy_short": "РИЛУ",
    "legacy_name_ru": "Рилузол",
    "doses": [
      50,
      100
    ],
    "default_dose": 50,
    "dose_unit": "мг",
    "max_dose": 100
  },
  "buspirone": {
    "id": "buspirone",
    "brand_name": "Buspar",
    "generic_name": "buspirone",
    "drug_class": "5-HT1A partial agonist (anxiolytic)",
    "indications": [
      "generalized anxiety disorder"
    ],
    "bindings": [
      {
        "receptor": "5HT1A",
        "ki_nM": 5.7,
        "type": "partial_agonist",
        "intrinsic_efficacy": 0.5,
        "source": "Loane & Bhatt 1996"
      },
      {
        "receptor": "D2",
        "ki_nM": 484,
        "type": "antagonist",
        "source": "Tallman et al. 1997"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#38bdf8",
    "region_targets": [
      "amygdala",
      "hippo",
      "raphe",
      "dlPFC"
    ],
    "legacy_short": "БУСП",
    "legacy_name_ru": "Буспирон",
    "doses": [
      5,
      7.5,
      10,
      15,
      30
    ],
    "default_dose": 10,
    "dose_unit": "мг",
    "max_dose": 60
  },
  "pridopidine": {
    "id": "pridopidine",
    "brand_name": "Pridopidine",
    "generic_name": "pridopidine",
    "drug_class": "σ1 receptor agonist",
    "indications": [
      "Huntington's disease (investigational)"
    ],
    "bindings": [
      {
        "receptor": "s1",
        "ki_nM": 70,
        "type": "partial_agonist",
        "intrinsic_efficacy": 0.8,
        "source": "Bhatt et al. 2019"
      },
      {
        "receptor": "D2",
        "ki_nM": 11800,
        "type": "antagonist",
        "source": "Ponten et al. 2010, very weak"
      }
    ],
    "pk": {
      "molecular_weight_g_mol": 0,
      "oral_bioavailability": 0,
      "protein_binding": 0,
      "brain_plasma_ratio": 0,
      "half_life_hours": 0
    },
    "color": "#f472b6",
    "region_targets": [
      "hippo",
      "dlPFC",
      "striatum"
    ],
    "legacy_short": "ПРИД",
    "legacy_name_ru": "Придопидин",
    "doses": [
      45,
      90,
      135
    ],
    "default_dose": 45,
    "dose_unit": "мг",
    "max_dose": 135
  }
};

/** Get a drug by ID */
export function getDrugV2(id: string): DrugSchemaV2 | undefined {
  return DRUGS_V2[id];
}

/** Get all drug IDs */
export function getAllDrugIdsV2(): string[] {
  return Object.keys(DRUGS_V2);
}
